from __future__ import annotations

from typing import Protocol

from .models import NameKind, NameRecord, Slip, SlipCreate, SlipPatch, Status, VerifyResult


class TimeslipsStore(Protocol):
    def status(self) -> Status: ...
    def list_names(self, kind: NameKind, q: str | None = None, limit: int = 100) -> list[NameRecord]: ...
    def get_slip(self, slip_id: str) -> Slip: ...
    def list_slips(
        self,
        *,
        date: str | None = None,
        client_nickname: str | None = None,
        timekeeper_nickname: str | None = None,
        billed: bool | None = None,
        limit: int = 100,
    ) -> list[Slip]: ...
    def create_slip(self, payload: SlipCreate) -> Slip: ...
    def update_slip(self, slip_id: str, patch: SlipPatch) -> Slip: ...
    def delete_slip(self, slip_id: str) -> None: ...
    def verify_slips(self, ids: list[str]) -> VerifyResult: ...
